platform :ios, '14.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  pod 'SDWebImage', '~> 5.20.0'
  pod 'ISVImageScrollView', '~> 0.3'
end

target 'PluginTests' do
  capacitor_pods
  pod 'SDWebImage', '~> 5.20.0'
  pod 'ISVImageScrollView', '~> 0.3'
end

# for SDWebImage, ISVImageScrollView, SDWebImage override the iOS deployment target
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
